[package]
name = "api_practice_en"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
actix-files = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.0"
uuid = { version = "1", features = ["v4", "serde"] }